import 'package:meno_fe_v2/modules/bible/domain/entities/book.dart';

const List<Book> allBooks = <Book>[
  Book(name: ["Gen", "Genesis"]),
  Book(name: ["Exod", "Exodus"]),
  Book(name: ["Lev", "Leviticus"]),
  Book(name: ["Num", "Numbers"]),
  Book(name: ["Deut", "Deuteronomy"]),
  Book(name: ["Josh", "Joshua"]),
  Book(name: ["Judg", "Judges"]),
  Book(name: ["Ruth", "Ruth"]),
  Book(name: ["1Sam", "1 Samuel"]),
  Book(name: ["2Sam", "2 Samuel"]),
  Book(name: ["1Kgs", "1 Kings"]),
  Book(name: ["2Kgs", "2 Kings"]),
  Book(name: ["1Chr", "1 Chronicles"]),
  Book(name: ["2Chr", "2 Chronicles"]),
  Book(name: ["Ezra", "Ezra"]),
  Book(name: ["Neh", "Nehemiah"]),
  Book(name: ["Esth", "Esther"]),
  Book(name: ["Job", "Job"]),
  Book(name: ["Ps", "Psalms"]),
  Book(name: ["Prov", "Proverbs"]),
  Book(name: ["Eccl", "Ecclesiastes"]),
  Book(name: ["Song", "Song of Solomon"]),
  Book(name: ["Isa", "Isaiah"]),
  Book(name: ["Jer", "Jeremiah"]),
  Book(name: ["Lam", "Lamentations"]),
  Book(name: ["Ezek", "Ezekiel"]),
  Book(name: ["Dan", "Daniel"]),
  Book(name: ["Hos", "Hosea"]),
  Book(name: ["Joel", "Joel"]),
  Book(name: ["Amos", "Amos"]),
  Book(name: ["Obad", "Obadiah"]),
  Book(name: ["Jona", "Jonah"]),
  Book(name: ["Mic", "Micah"]),
  Book(name: ["Nah", "Nahum"]),
  Book(name: ["Hab", "Habakkuk"]),
  Book(name: ["Zeph", "Zephaniah"]),
  Book(name: ["Hag", "Haggai"]),
  Book(name: ["Zech", "Zechariah"]),
  Book(name: ["Mal", "Malachi"]),
  Book(name: ["Matt", "Matthew"]),
  Book(name: ["Mark", "Mark"]),
  Book(name: ["Luke", "Luke"]),
  Book(name: ["John", "John"]),
  Book(name: ["Acts", "Acts of the Apostles"]),
  Book(name: ["Rom", "Romans"]),
  Book(name: ["1Cor", "1 Corinthians"]),
  Book(name: ["2Cor", "2 Corinthians"]),
  Book(name: ["Gal", "Galatians"]),
  Book(name: ["Eph", "Ephesians"]),
  Book(name: ["Phil", "Philippians"]),
  Book(name: ["Col", "Colossians"]),
  Book(name: ["1Thess", "1 Thessalonians"]),
  Book(name: ["2Thess", "2 Thessalonians"]),
  Book(name: ["1Tim", "1 Timothy"]),
  Book(name: ["2Tim", "2 Timothy"]),
  Book(name: ["Titus", "Titus"]),
  Book(name: ["Phlm", "Philemon"]),
  Book(name: ["Heb", "Hebrews"]),
  Book(name: ["Jas", "James"]),
  Book(name: ["1Pet", "1 Peter"]),
  Book(name: ["2Pet", "2 Peter"]),
  Book(name: ["1John", "1 John"]),
  Book(name: ["2John", "2 John"]),
  Book(name: ["3John", "3 John"]),
  Book(name: ["Jude", "Jude"]),
  Book(name: ["Rev", "Revelation"]),
];
