import 'package:meno_fe_v2/modules/bible/domain/entities/book.dart';

const List<Book> books = <Book>[
  Book(book: ["Gen", "Genesis"]),
  Book(book: ["Exod", "Exodus"]),
  Book(book: ["Lev", "Leviticus"]),
  Book(book: ["Num", "Numbers"]),
  Book(book: ["Deut", "Deuteronomy"]),
  Book(book: ["Josh", "Joshua"]),
  Book(book: ["Judg", "Judges"]),
  Book(book: ["Ruth", "Ruth"]),
  Book(book: ["1Sam", "1 Samuel"]),
  Book(book: ["2Sam", "2 Samuel"]),
  Book(book: ["1Kgs", "1 Kings"]),
  Book(book: ["2Kgs", "2 Kings"]),
  Book(book: ["1Chr", "1 Chronicles"]),
  Book(book: ["2Chr", "2 Chronicles"]),
  Book(book: ["Ezra", "Ezra"]),
  Book(book: ["Neh", "Nehemiah"]),
  Book(book: ["Esth", "Esther"]),
  Book(book: ["Job", "Job"]),
  Book(book: ["Ps", "Psalms"]),
  Book(book: ["Prov", "Proverbs"]),
  Book(book: ["Eccl", "Ecclesiastes"]),
  Book(book: ["Song", "Song of Solomon"]),
  Book(book: ["Isa", "Isaiah"]),
  Book(book: ["Jer", "Jeremiah"]),
  Book(book: ["Lam", "Lamentations"]),
  Book(book: ["Ezek", "Ezekiel"]),
  Book(book: ["Dan", "Daniel"]),
  Book(book: ["Hos", "Hosea"]),
  Book(book: ["Joel", "Joel"]),
  Book(book: ["Amos", "Amos"]),
  Book(book: ["Obad", "Obadiah"]),
  Book(book: ["Jona", "Jonah"]),
  Book(book: ["Mic", "Micah"]),
  Book(book: ["Nah", "Nahum"]),
  Book(book: ["Hab", "Habakkuk"]),
  Book(book: ["Zeph", "Zephaniah"]),
  Book(book: ["Hag", "Haggai"]),
  Book(book: ["Zech", "Zechariah"]),
  Book(book: ["Mal", "Malachi"]),
  Book(book: ["Matt", "Matthew"]),
  Book(book: ["Mark", "Mark"]),
  Book(book: ["Luke", "Luke"]),
  Book(book: ["John", "John"]),
  Book(book: ["Acts", "Acts of the Apostles"]),
  Book(book: ["Rom", "Romans"]),
  Book(book: ["1Cor", "1 Corinthians"]),
  Book(book: ["2Cor", "2 Corinthians"]),
  Book(book: ["Gal", "Galatians"]),
  Book(book: ["Eph", "Ephesians"]),
  Book(book: ["Phil", "Philippians"]),
  Book(book: ["Col", "Colossians"]),
  Book(book: ["1Thess", "1 Thessalonians"]),
  Book(book: ["2Thess", "2 Thessalonians"]),
  Book(book: ["1Tim", "1 Timothy"]),
  Book(book: ["2Tim", "2 Timothy"]),
  Book(book: ["Titus", "Titus"]),
  Book(book: ["Phlm", "Philemon"]),
  Book(book: ["Heb", "Hebrews"]),
  Book(book: ["Jas", "James"]),
  Book(book: ["1Pet", "1 Peter"]),
  Book(book: ["2Pet", "2 Peter"]),
  Book(book: ["1John", "1 John"]),
  Book(book: ["2John", "2 John"]),
  Book(book: ["3John", "3 John"]),
  Book(book: ["Jude", "Jude"]),
  Book(book: ["Rev", "Revelation"]),
];
