import 'package:meno_fe_v2/modules/bible/domain/entities/book.dart';

const List<Book> allOldTestamentBooks = <Book>[
  Book(name: ["Gen", "Genesis"], numberOfChapters: 50),
  Book(name: ["Exod", "Exodus"], numberOfChapters: 40),
  Book(name: ["Lev", "Leviticus"], numberOfChapters: 27),
  Book(name: ["Num", "Numbers"], numberOfChapters: 36),
  Book(name: ["Deut", "Deuteronomy"], numberOfChapters: 34),
  Book(name: ["Josh", "Joshua"], numberOfChapters: 24),
  Book(name: ["Judg", "Judges"], numberOfChapters: 21),
  Book(name: ["Ruth", "Ruth"], numberOfChapters: 4),
  Book(name: ["1Sam", "1 Samuel"], numberOfChapters: 31),
  Book(name: ["2Sam", "2 Samuel"], numberOfChapters: 24),
  Book(name: ["1Kgs", "1 Kings"], numberOfChapters: 22),
  Book(name: ["2Kgs", "2 Kings"], numberOfChapters: 25),
  Book(name: ["1Chr", "1 Chronicles"], numberOfChapters: 29),
  Book(name: ["2Chr", "2 Chronicles"], numberOfChapters: 36),
  Book(name: ["Ezra", "Ezra"], numberOfChapters: 10),
  Book(name: ["Neh", "Nehemiah"], numberOfChapters: 13),
  Book(name: ["Esth", "Esther"], numberOfChapters: 10),
  Book(name: ["Job", "Job"], numberOfChapters: 42),
  Book(name: ["Ps", "Psalms"], numberOfChapters: 150),
  Book(name: ["Prov", "Proverbs"], numberOfChapters: 31),
  Book(name: ["Eccl", "Ecclesiastes"], numberOfChapters: 12),
  Book(name: ["Song", "Song of Solomon"], numberOfChapters: 8),
  Book(name: ["Isa", "Isaiah"], numberOfChapters: 66),
  Book(name: ["Jer", "Jeremiah"], numberOfChapters: 52),
  Book(name: ["Lam", "Lamentations"], numberOfChapters: 5),
  Book(name: ["Ezek", "Ezekiel"], numberOfChapters: 48),
  Book(name: ["Dan", "Daniel"], numberOfChapters: 12),
  Book(name: ["Hos", "Hosea"], numberOfChapters: 14),
  Book(name: ["Joel", "Joel"], numberOfChapters: 3),
  Book(name: ["Amos", "Amos"], numberOfChapters: 9),
  Book(name: ["Obad", "Obadiah"], numberOfChapters: 1),
  Book(name: ["Jona", "Jonah"], numberOfChapters: 4),
  Book(name: ["Mic", "Micah"], numberOfChapters: 7),
  Book(name: ["Nah", "Nahum"], numberOfChapters: 3),
  Book(name: ["Hab", "Habakkuk"], numberOfChapters: 3),
  Book(name: ["Zeph", "Zephaniah"], numberOfChapters: 3),
  Book(name: ["Hag", "Haggai"], numberOfChapters: 2),
  Book(name: ["Zech", "Zechariah"], numberOfChapters: 14),
  Book(name: ["Mal", "Malachi"], numberOfChapters: 4),
];

const allNewTestamentBooks = <Book>[
  Book(name: ["Matt", "Matthew"], numberOfChapters: 28),
  Book(name: ["Mark", "Mark"], numberOfChapters: 16),
  Book(name: ["Luke", "Luke"], numberOfChapters: 24),
  Book(name: ["John", "John"], numberOfChapters: 21),
  Book(name: ["Acts", "Acts of the Apostles"], numberOfChapters: 28),
  Book(name: ["Rom", "Romans"], numberOfChapters: 16),
  Book(name: ["1Cor", "1 Corinthians"], numberOfChapters: 16),
  Book(name: ["2Cor", "2 Corinthians"], numberOfChapters: 13),
  Book(name: ["Gal", "Galatians"], numberOfChapters: 6),
  Book(name: ["Eph", "Ephesians"], numberOfChapters: 6),
  Book(name: ["Phil", "Philippians"], numberOfChapters: 50),
  Book(name: ["Col", "Colossians"], numberOfChapters: 4),
  Book(name: ["1Thess", "1 Thessalonians"], numberOfChapters: 5),
  Book(name: ["2Thess", "2 Thessalonians"], numberOfChapters: 3),
  Book(name: ["1Tim", "1 Timothy"], numberOfChapters: 6),
  Book(name: ["2Tim", "2 Timothy"], numberOfChapters: 4),
  Book(name: ["Titus", "Titus"], numberOfChapters: 3),
  Book(name: ["Phlm", "Philemon"], numberOfChapters: 1),
  Book(name: ["Heb", "Hebrews"], numberOfChapters: 13),
  Book(name: ["Jas", "James"], numberOfChapters: 5),
  Book(name: ["1Pet", "1 Peter"], numberOfChapters: 5),
  Book(name: ["2Pet", "2 Peter"], numberOfChapters: 3),
  Book(name: ["1John", "1 John"], numberOfChapters: 5),
  Book(name: ["2John", "2 John"], numberOfChapters: 1),
  Book(name: ["3John", "3 John"], numberOfChapters: 1),
  Book(name: ["Jude", "Jude"], numberOfChapters: 1),
  Book(name: ["Rev", "Revelation"], numberOfChapters: 22),
];

const allBooks = <Book>[
 Book(name: ["Gen", "Genesis"], numberOfChapters: 50),
  Book(name: ["Exod", "Exodus"], numberOfChapters: 40),
  Book(name: ["Lev", "Leviticus"], numberOfChapters: 27),
  Book(name: ["Num", "Numbers"], numberOfChapters: 36),
  Book(name: ["Deut", "Deuteronomy"], numberOfChapters: 34),
  Book(name: ["Josh", "Joshua"], numberOfChapters: 24),
  Book(name: ["Judg", "Judges"], numberOfChapters: 21),
  Book(name: ["Ruth", "Ruth"], numberOfChapters: 4),
  Book(name: ["1Sam", "1 Samuel"], numberOfChapters: 31),
  Book(name: ["2Sam", "2 Samuel"], numberOfChapters: 24),
  Book(name: ["1Kgs", "1 Kings"], numberOfChapters: 22),
  Book(name: ["2Kgs", "2 Kings"], numberOfChapters: 25),
  Book(name: ["1Chr", "1 Chronicles"], numberOfChapters: 29),
  Book(name: ["2Chr", "2 Chronicles"], numberOfChapters: 36),
  Book(name: ["Ezra", "Ezra"], numberOfChapters: 10),
  Book(name: ["Neh", "Nehemiah"], numberOfChapters: 13),
  Book(name: ["Esth", "Esther"], numberOfChapters: 10),
  Book(name: ["Job", "Job"], numberOfChapters: 42),
  Book(name: ["Ps", "Psalms"], numberOfChapters: 150),
  Book(name: ["Prov", "Proverbs"], numberOfChapters: 31),
  Book(name: ["Eccl", "Ecclesiastes"], numberOfChapters: 12),
  Book(name: ["Song", "Song of Solomon"], numberOfChapters: 8),
  Book(name: ["Isa", "Isaiah"], numberOfChapters: 66),
  Book(name: ["Jer", "Jeremiah"], numberOfChapters: 52),
  Book(name: ["Lam", "Lamentations"], numberOfChapters: 5),
  Book(name: ["Ezek", "Ezekiel"], numberOfChapters: 48),
  Book(name: ["Dan", "Daniel"], numberOfChapters: 12),
  Book(name: ["Hos", "Hosea"], numberOfChapters: 14),
  Book(name: ["Joel", "Joel"], numberOfChapters: 3),
  Book(name: ["Amos", "Amos"], numberOfChapters: 9),
  Book(name: ["Obad", "Obadiah"], numberOfChapters: 1),
  Book(name: ["Jona", "Jonah"], numberOfChapters: 4),
  Book(name: ["Mic", "Micah"], numberOfChapters: 7),
  Book(name: ["Nah", "Nahum"], numberOfChapters: 3),
  Book(name: ["Hab", "Habakkuk"], numberOfChapters: 3),
  Book(name: ["Zeph", "Zephaniah"], numberOfChapters: 3),
  Book(name: ["Hag", "Haggai"], numberOfChapters: 2),
  Book(name: ["Zech", "Zechariah"], numberOfChapters: 14),
  Book(name: ["Mal", "Malachi"], numberOfChapters: 4),
  Book(name: ["Matt", "Matthew"], numberOfChapters: 28),
  Book(name: ["Mark", "Mark"], numberOfChapters: 16),
  Book(name: ["Luke", "Luke"], numberOfChapters: 24),
  Book(name: ["John", "John"], numberOfChapters: 21),
  Book(name: ["Acts", "Acts of the Apostles"], numberOfChapters: 28),
  Book(name: ["Rom", "Romans"], numberOfChapters: 16),
  Book(name: ["1Cor", "1 Corinthians"], numberOfChapters: 16),
  Book(name: ["2Cor", "2 Corinthians"], numberOfChapters: 13),
  Book(name: ["Gal", "Galatians"], numberOfChapters: 6),
  Book(name: ["Eph", "Ephesians"], numberOfChapters: 6),
  Book(name: ["Phil", "Philippians"], numberOfChapters: 50),
  Book(name: ["Col", "Colossians"], numberOfChapters: 4),
  Book(name: ["1Thess", "1 Thessalonians"], numberOfChapters: 5),
  Book(name: ["2Thess", "2 Thessalonians"], numberOfChapters: 3),
  Book(name: ["1Tim", "1 Timothy"], numberOfChapters: 6),
  Book(name: ["2Tim", "2 Timothy"], numberOfChapters: 4),
  Book(name: ["Titus", "Titus"], numberOfChapters: 3),
  Book(name: ["Phlm", "Philemon"], numberOfChapters: 1),
  Book(name: ["Heb", "Hebrews"], numberOfChapters: 13),
  Book(name: ["Jas", "James"], numberOfChapters: 5),
  Book(name: ["1Pet", "1 Peter"], numberOfChapters: 5),
  Book(name: ["2Pet", "2 Peter"], numberOfChapters: 3),
  Book(name: ["1John", "1 John"], numberOfChapters: 5),
  Book(name: ["2John", "2 John"], numberOfChapters: 1),
  Book(name: ["3John", "3 John"], numberOfChapters: 1),
  Book(name: ["Jude", "Jude"], numberOfChapters: 1),
  Book(name: ["Rev", "Revelation"], numberOfChapters: 22),
];
