import 'package:meno_fe_v2/modules/bible/domain/entities/book.dart';

const List<Book> allOldTestamentBooks = <Book>[
  Book(name: ["Gen", "Genesis"], numberOfChapters: 50),
  Book(name: ["Exod", "Exodus"], numberOfChapters: 40),
  Book(name: ["Lev", "Leviticus"], numberOfChapters: 27),
  Book(name: ["Num", "Numbers"], numberOfChapters: 36),
  Book(name: ["Deut", "Deuteronomy"], numberOfChapters: 34),
  Book(name: ["Josh", "Joshua"], numberOfChapters: 24),
  Book(name: ["Judg", "Judges"], numberOfChapters: 21),
  Book(name: ["Ruth", "Ruth"], numberOfChapters: 4),
  Book(name: ["1Sam", "1 Samuel"], numberOfChapters: 31),
  Book(name: ["2Sam", "2 Samuel"], numberOfChapters: 24),
  Book(name: ["1Kgs", "1 Kings"], numberOfChapters: 22),
  Book(name: ["2Kgs", "2 Kings"], numberOfChapters: 25),
  Book(name: ["1Chr", "1 Chronicles"], numberOfChapters: 29),
  Book(name: ["2Chr", "2 Chronicles"], numberOfChapters: 36),
  Book(name: ["Ezra", "Ezra"], numberOfChapters: 10),
  Book(name: ["Neh", "Nehemiah"], numberOfChapters: 13),
  Book(name: ["Esth", "Esther"], numberOfChapters: 10),
  Book(name: ["Job", "Job"], numberOfChapters: 42),
  Book(name: ["Ps", "Psalms"], numberOfChapters: 150),
  Book(name: ["Prov", "Proverbs"], numberOfChapters: 31),
  Book(name: ["Eccl", "Ecclesiastes"], numberOfChapters: 12),
  Book(name: ["Song", "Song of Solomon"], numberOfChapters: 8),
  Book(name: ["Isa", "Isaiah"], numberOfChapters: 66),
  Book(name: ["Jer", "Jeremiah"], numberOfChapters: 52),
  Book(name: ["Lam", "Lamentations"], numberOfChapters: 5),
  Book(name: ["Ezek", "Ezekiel"], numberOfChapters: 48),
  Book(name: ["Dan", "Daniel"], numberOfChapters: 12),
  Book(name: ["Hos", "Hosea"], numberOfChapters: 14),
  Book(name: ["Joel", "Joel"], numberOfChapters: 3),
  Book(name: ["Amos", "Amos"], numberOfChapters: 9),
  Book(name: ["Obad", "Obadiah"], numberOfChapters: 1),
  Book(name: ["Jona", "Jonah"], numberOfChapters: 4),
  Book(name: ["Mic", "Micah"], numberOfChapters: 7),
  Book(name: ["Nah", "Nahum"], numberOfChapters: 3),
  Book(name: ["Hab", "Habakkuk"], numberOfChapters: 3),
  Book(name: ["Zeph", "Zephaniah"], numberOfChapters: 3),
  Book(name: ["Hag", "Haggai"], numberOfChapters: 2),
  Book(name: ["Zech", "Zechariah"], numberOfChapters: 14),
  Book(name: ["Mal", "Malachi"], numberOfChapters: 4),
];

const allNewTestamentBooks = <Book>[
  Book(name: ["Matt", "Matthew"], numberOfChapters: 28),
  Book(name: ["Mark", "Mark"], numberOfChapters: 16),
  Book(name: ["Luke", "Luke"], numberOfChapters: 24),
  Book(name: ["John", "John"], numberOfChapters: 21),
  Book(name: ["Acts", "Acts of the Apostles"], numberOfChapters: 28),
  Book(name: ["Rom", "Romans"], numberOfChapters: 16),
  Book(name: ["1Cor", "1 Corinthians"], numberOfChapters: 16),
  Book(name: ["2Cor", "2 Corinthians"], numberOfChapters: 13),
  Book(name: ["Gal", "Galatians"], numberOfChapters: 6),
  Book(name: ["Eph", "Ephesians"], numberOfChapters: 6),
  Book(name: ["Phil", "Philippians"], numberOfChapters: 50),
  Book(name: ["Col", "Colossians"], numberOfChapters: 4),
  Book(name: ["1Thess", "1 Thessalonians"], numberOfChapters: 5),
  Book(name: ["2Thess", "2 Thessalonians"], numberOfChapters: 3),
  Book(name: ["1Tim", "1 Timothy"], numberOfChapters: 6),
  Book(name: ["2Tim", "2 Timothy"], numberOfChapters: 4),
  Book(name: ["Titus", "Titus"], numberOfChapters: 3),
  Book(name: ["Phlm", "Philemon"], numberOfChapters: 1),
  Book(name: ["Heb", "Hebrews"], numberOfChapters: 13),
  Book(name: ["Jas", "James"], numberOfChapters: 5),
  Book(name: ["1Pet", "1 Peter"], numberOfChapters: 5),
  Book(name: ["2Pet", "2 Peter"], numberOfChapters: 3),
  Book(name: ["1John", "1 John"], numberOfChapters: 5),
  Book(name: ["2John", "2 John"], numberOfChapters: 1),
  Book(name: ["3John", "3 John"], numberOfChapters: 1),
  Book(name: ["Jude", "Jude"], numberOfChapters: 1),
  Book(name: ["Rev", "Revelation"], numberOfChapters: 22),
];

const allBooks = <Book>[
  Book(name: ["Gen", "Genesis"], numberOfChapters: 50),
  Book(name: ["Exod", "Exodus"], numberOfChapters: 40),
  Book(name: ["Lev", "Leviticus"], numberOfChapters: 27),
  Book(name: ["Num", "Numbers"], numberOfChapters: 36),
  Book(name: ["Deut", "Deuteronomy"], numberOfChapters: 34),
  Book(name: ["Josh", "Joshua"], numberOfChapters: 24),
  Book(name: ["Judg", "Judges"], numberOfChapters: 21),
  Book(name: ["Ruth", "Ruth"], numberOfChapters: 4),
  Book(name: ["1Sam", "1 Samuel"], numberOfChapters: 31),
  Book(name: ["2Sam", "2 Samuel"], numberOfChapters: 24),
  Book(name: ["1Kgs", "1 Kings"], numberOfChapters: 22),
  Book(name: ["2Kgs", "2 Kings"], numberOfChapters: 25),
  Book(name: ["1Chr", "1 Chronicles"], numberOfChapters: 29),
  Book(name: ["2Chr", "2 Chronicles"], numberOfChapters: 36),
  Book(name: ["Ezra", "Ezra"], numberOfChapters: 10),
  Book(name: ["Neh", "Nehemiah"], numberOfChapters: 13),
  Book(name: ["Esth", "Esther"], numberOfChapters: 10),
  Book(name: ["Job", "Job"], numberOfChapters: 42),
  Book(name: ["Ps", "Psalms"], numberOfChapters: 150),
  Book(name: ["Prov", "Proverbs"], numberOfChapters: 31),
  Book(name: ["Eccl", "Ecclesiastes"], numberOfChapters: 12),
  Book(name: ["Song", "Song of Solomon"], numberOfChapters: 8),
  Book(name: ["Isa", "Isaiah"], numberOfChapters: 66),
  Book(name: ["Jer", "Jeremiah"], numberOfChapters: 52),
  Book(name: ["Lam", "Lamentations"], numberOfChapters: 5),
  Book(name: ["Ezek", "Ezekiel"], numberOfChapters: 48),
  Book(name: ["Dan", "Daniel"], numberOfChapters: 12),
  Book(name: ["Hos", "Hosea"], numberOfChapters: 14),
  Book(name: ["Joel", "Joel"], numberOfChapters: 3),
  Book(name: ["Amos", "Amos"], numberOfChapters: 9),
  Book(name: ["Obad", "Obadiah"], numberOfChapters: 1),
  Book(name: ["Jona", "Jonah"], numberOfChapters: 4),
  Book(name: ["Mic", "Micah"], numberOfChapters: 7),
  Book(name: ["Nah", "Nahum"], numberOfChapters: 3),
  Book(name: ["Hab", "Habakkuk"], numberOfChapters: 3),
  Book(name: ["Zeph", "Zephaniah"], numberOfChapters: 3),
  Book(name: ["Hag", "Haggai"], numberOfChapters: 2),
  Book(name: ["Zech", "Zechariah"], numberOfChapters: 14),
  Book(name: ["Mal", "Malachi"], numberOfChapters: 4),
  Book(name: ["Matt", "Matthew"], numberOfChapters: 28),
  Book(name: ["Mark", "Mark"], numberOfChapters: 16),
  Book(name: ["Luke", "Luke"], numberOfChapters: 24),
  Book(name: ["John", "John"], numberOfChapters: 21),
  Book(name: ["Acts", "Acts of the Apostles"], numberOfChapters: 28),
  Book(name: ["Rom", "Romans"], numberOfChapters: 16),
  Book(name: ["1Cor", "1 Corinthians"], numberOfChapters: 16),
  Book(name: ["2Cor", "2 Corinthians"], numberOfChapters: 13),
  Book(name: ["Gal", "Galatians"], numberOfChapters: 6),
  Book(name: ["Eph", "Ephesians"], numberOfChapters: 6),
  Book(name: ["Phil", "Philippians"], numberOfChapters: 50),
  Book(name: ["Col", "Colossians"], numberOfChapters: 4),
  Book(name: ["1Thess", "1 Thessalonians"], numberOfChapters: 5),
  Book(name: ["2Thess", "2 Thessalonians"], numberOfChapters: 3),
  Book(name: ["1Tim", "1 Timothy"], numberOfChapters: 6),
  Book(name: ["2Tim", "2 Timothy"], numberOfChapters: 4),
  Book(name: ["Titus", "Titus"], numberOfChapters: 3),
  Book(name: ["Phlm", "Philemon"], numberOfChapters: 1),
  Book(name: ["Heb", "Hebrews"], numberOfChapters: 13),
  Book(name: ["Jas", "James"], numberOfChapters: 5),
  Book(name: ["1Pet", "1 Peter"], numberOfChapters: 5),
  Book(name: ["2Pet", "2 Peter"], numberOfChapters: 3),
  Book(name: ["1John", "1 John"], numberOfChapters: 5),
  Book(name: ["2John", "2 John"], numberOfChapters: 1),
  Book(name: ["3John", "3 John"], numberOfChapters: 1),
  Book(name: ["Jude", "Jude"], numberOfChapters: 1),
  Book(name: ["Rev", "Revelation"], numberOfChapters: 22),
];

Map<List<String>, int> newAllBooks = {
  ["Gen", "Genesis"]: 50,
  ["Exod", "Exodus"]: 40,
  ["Lev", "Leviticus"]: 27,
  ["Num", "Numbers"]: 36,
  ["Deut", "Deuteronomy"]: 34,
  ["Josh", "Joshua"]: 24,
  ["Judg", "Judges"]: 21,
  ["Ruth", "Ruth"]: 4,
  ["1Sam", "1 Samuel"]: 31,
  ["2Sam", "2 Samuel"]: 24,
  ["1Kgs", "1 Kings"]: 22,
  ["2Kgs", "2 Kings"]: 25,
  ["1Chr", "1 Chronicles"]: 29,
  ["2Chr", "2 Chronicles"]: 36,
  ["Ezra", "Ezra"]: 10,
  ["Neh", "Nehemiah"]: 13,
  ["Esth", "Esther"]: 10,
  ["Job", "Job"]: 42,
  ["Ps", "Psalms"]: 150,
  ["Prov", "Proverbs"]: 31,
  ["Eccl", "Ecclesiastes"]: 12,
  ["Song", "Song of Solomon"]: 8,
  ["Isa", "Isaiah"]: 66,
  ["Jer", "Jeremiah"]: 52,
  ["Lam", "Lamentations"]: 5,
  ["Ezek", "Ezekiel"]: 48,
  ["Dan", "Daniel"]: 12,
  ["Hos", "Hosea"]: 14,
  ["Joel", "Joel"]: 3,
  ["Amos", "Amos"]: 9,
  ["Obad", "Obadiah"]: 1,
  ["Jona", "Jonah"]: 4,
  ["Mic", "Micah"]: 7,
  ["Nah", "Nahum"]: 3,
  ["Hab", "Habakkuk"]: 3,
  ["Zeph", "Zephaniah"]: 3,
  ["Hag", "Haggai"]: 2,
  ["Zech", "Zechariah"]: 14,
  ["Mal", "Malachi"]: 4,
  ["Matt", "Matthew"]: 28,
  ["Mark", "Mark"]: 16,
  ["Luke", "Luke"]: 24,
  ["John", "John"]: 21,
  ["Acts", "Acts of the Apostles"]: 28,
  ["Rom", "Romans"]: 16,
  ["1Cor", "1 Corinthians"]: 16,
  ["2Cor", "2 Corinthians"]: 13,
  ["Gal", "Galatians"]: 6,
  ["Eph", "Ephesians"]: 6,
  ["Phil", "Philippians"]: 50,
  ["Col", "Colossians"]: 4,
  ["1Thess", "1 Thessalonians"]: 5,
  ["2Thess", "2 Thessalonians"]: 3,
  ["1Tim", "1 Timothy"]: 6,
  ["2Tim", "2 Timothy"]: 4,
  ["Titus", "Titus"]: 3,
  ["Phlm", "Philemon"]: 1,
  ["Heb", "Hebrews"]: 13,
  ["Jas", "James"]: 5,
  ["1Pet", "1 Peter"]: 5,
  ["2Pet", "2 Peter"]: 3,
  ["1John", "1 John"]: 5,
  ["2John", "2 John"]: 1,
  ["3John", "3 John"]: 1,
  ["Jude", "Jude"]: 1,
  ["Rev", "Revelation"]: 22,
};

Map<List<String>, int> oldBooks = {
  ["Gen", "Genesis"]: 50,
  ["Exod", "Exodus"]: 40,
  ["Lev", "Leviticus"]: 27,
  ["Num", "Numbers"]: 36,
  ["Deut", "Deuteronomy"]: 34,
  ["Josh", "Joshua"]: 24,
  ["Judg", "Judges"]: 21,
  ["Ruth", "Ruth"]: 4,
  ["1Sam", "1 Samuel"]: 31,
  ["2Sam", "2 Samuel"]: 24,
  ["1Kgs", "1 Kings"]: 22,
  ["2Kgs", "2 Kings"]: 25,
  ["1Chr", "1 Chronicles"]: 29,
  ["2Chr", "2 Chronicles"]: 36,
  ["Ezra", "Ezra"]: 10,
  ["Neh", "Nehemiah"]: 13,
  ["Esth", "Esther"]: 10,
  ["Job", "Job"]: 42,
  ["Ps", "Psalms"]: 150,
  ["Prov", "Proverbs"]: 31,
  ["Eccl", "Ecclesiastes"]: 12,
  ["Song", "Song of Solomon"]: 8,
  ["Isa", "Isaiah"]: 66,
  ["Jer", "Jeremiah"]: 52,
  ["Lam", "Lamentations"]: 5,
  ["Ezek", "Ezekiel"]: 48,
  ["Dan", "Daniel"]: 12,
  ["Hos", "Hosea"]: 14,
  ["Joel", "Joel"]: 3,
  ["Amos", "Amos"]: 9,
  ["Obad", "Obadiah"]: 1,
  ["Jona", "Jonah"]: 4,
  ["Mic", "Micah"]: 7,
  ["Nah", "Nahum"]: 3,
  ["Hab", "Habakkuk"]: 3,
  ["Zeph", "Zephaniah"]: 3,
  ["Hag", "Haggai"]: 2,
  ["Zech", "Zechariah"]: 14,
  ["Mal", "Malachi"]: 4,
};

Map<List<String>, int> newBooks = {
  ["Matt", "Matthew"]: 28,
  ["Mark", "Mark"]: 16,
  ["Luke", "Luke"]: 24,
  ["John", "John"]: 21,
  ["Acts", "Acts of the Apostles"]: 28,
  ["Rom", "Romans"]: 16,
  ["1Cor", "1 Corinthians"]: 16,
  ["2Cor", "2 Corinthians"]: 13,
  ["Gal", "Galatians"]: 6,
  ["Eph", "Ephesians"]: 6,
  ["Phil", "Philippians"]: 50,
  ["Col", "Colossians"]: 4,
  ["1Thess", "1 Thessalonians"]: 5,
  ["2Thess", "2 Thessalonians"]: 3,
  ["1Tim", "1 Timothy"]: 6,
  ["2Tim", "2 Timothy"]: 4,
  ["Titus", "Titus"]: 3,
  ["Phlm", "Philemon"]: 1,
  ["Heb", "Hebrews"]: 13,
  ["Jas", "James"]: 5,
  ["1Pet", "1 Peter"]: 5,
  ["2Pet", "2 Peter"]: 3,
  ["1John", "1 John"]: 5,
  ["2John", "2 John"]: 1,
  ["3John", "3 John"]: 1,
  ["Jude", "Jude"]: 1,
  ["Rev", "Revelation"]: 22,
};
