// Mocks generated by Mockito 5.3.2 from annotations
// in meno_fe_v2/test/modules/auth/infrastructure/auth_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:meno_fe_v2/core/responses/auth_response.dart' as _i2;
import 'package:meno_fe_v2/modules/auth/infrastructure/datasources/local/auth_local_datasource.dart'
    as _i3;
import 'package:meno_fe_v2/modules/auth/infrastructure/datasources/mapper/user_credentials_mapper.dart'
    as _i8;
import 'package:meno_fe_v2/modules/auth/infrastructure/datasources/remote/auth_remote_datasource.dart'
    as _i6;
import 'package:meno_fe_v2/modules/auth/infrastructure/dtos/user_credentials_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i3.AuthLocalDatasource {
  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteCredentials() => (super.noSuchMethod(
        Invocation.method(
          #deleteCredentials,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteCredentialToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteCredentialToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i5.UserCredentialsDto?> getCredentials() => (super.noSuchMethod(
        Invocation.method(
          #getCredentials,
          [],
        ),
        returnValue: _i4.Future<_i5.UserCredentialsDto?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.UserCredentialsDto?>.value(),
      ) as _i4.Future<_i5.UserCredentialsDto?>);
  @override
  _i4.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
  @override
  _i4.Future<void> storeCredentials(_i5.UserCredentialsDto? dto) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCredentials,
          [dto],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> storeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i6.AuthRemoteDatasource {
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> register({
    required String? fullName,
    String? bio,
    required String? email,
    required String? password,
    _i7.File? image,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #bio: bio,
            #email: email,
            #password: password,
            #image: image,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #fullName: fullName,
              #bio: bio,
              #email: email,
              #password: password,
              #image: image,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #fullName: fullName,
              #bio: bio,
              #email: email,
              #password: password,
              #image: image,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> googleSignUp(
          String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleSignUp,
          [idToken],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleSignUp,
            [idToken],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleSignUp,
            [idToken],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>> googleSignIn(
          String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #googleSignIn,
          [idToken],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
            _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleSignIn,
            [idToken],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto>(
          this,
          Invocation.method(
            #googleSignIn,
            [idToken],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>> verify({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [],
          {
            #email: email,
            #code: code,
          },
        ),
        returnValue:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #verify,
            [],
            {
              #email: email,
              #code: code,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #verify,
            [],
            {
              #email: email,
              #code: code,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>> changePassword({
    required String? newPassword,
    required String? currentPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #newPassword: newPassword,
            #currentPassword: currentPassword,
          },
        ),
        returnValue:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #newPassword: newPassword,
              #currentPassword: currentPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #newPassword: newPassword,
              #currentPassword: currentPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>> forgotPassword(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#email: email},
        ),
        returnValue:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>> resetPassword({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #email: email,
            #code: code,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>);
  @override
  _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>> requestOTP({
    required String? type,
    required String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestOTP,
          [],
          {
            #type: type,
            #email: email,
          },
        ),
        returnValue:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #requestOTP,
            [],
            {
              #type: type,
              #email: email,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>.value(
                _FakeAuthResponse_0<_i5.UserCredentialsDto?>(
          this,
          Invocation.method(
            #requestOTP,
            [],
            {
              #type: type,
              #email: email,
            },
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.UserCredentialsDto?>>);
}

/// A class which mocks [UserCredentialsMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredentialsMapper extends _i1.Mock
    implements _i8.UserCredentialsMapper {}
