// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKxyXzMepnsmS2kT9cVFYHN7zRoJZaEY',
    appId: '1:10193767589:web:f02a237c0ccedb0e45d14c',
    messagingSenderId: '10193767589',
    projectId: 'meno-fe',
    authDomain: 'meno-fe.firebaseapp.com',
    storageBucket: 'meno-fe.appspot.com',
    measurementId: 'G-EW1TM51GNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmL4Atwkmws3phMMqDA81NfdRFCENq4Ho',
    appId: '1:10193767589:android:471fd2ba2db943bb45d14c',
    messagingSenderId: '10193767589',
    projectId: 'meno-fe',
    storageBucket: 'meno-fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBEsQEwUEmZ-6BcGXBDs2O2KqBTvdo3M',
    appId: '1:10193767589:ios:c197a3c44eb6aa5745d14c',
    messagingSenderId: '10193767589',
    projectId: 'meno-fe',
    storageBucket: 'meno-fe.appspot.com',
    androidClientId: '10193767589-bgfhcdkrn598u3m2dfak4c11dpt8cff9.apps.googleusercontent.com',
    iosClientId: '10193767589-acu08vga8sqcpj3vc5l1cml8qonsc72o.apps.googleusercontent.com',
    iosBundleId: 'com.example.menoFeV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALBEsQEwUEmZ-6BcGXBDs2O2KqBTvdo3M',
    appId: '1:10193767589:ios:c197a3c44eb6aa5745d14c',
    messagingSenderId: '10193767589',
    projectId: 'meno-fe',
    storageBucket: 'meno-fe.appspot.com',
    androidClientId: '10193767589-bgfhcdkrn598u3m2dfak4c11dpt8cff9.apps.googleusercontent.com',
    iosClientId: '10193767589-acu08vga8sqcpj3vc5l1cml8qonsc72o.apps.googleusercontent.com',
    iosBundleId: 'com.example.menoFeV2',
  );
}
